Shele
rsh-12/interview4j pull request #13
Opened 2021-08-08 17:01 UTC by Ivanshelemeh

Проблема репо показывает нулл в тесте типо спринг не находит бин такой

2021-08-10 03:15 UTC, rsh-12 requested changes

2021-08-10 03:15 UTC, rsh-12 commented on backend/interview4j/src/main/java/ru/interview4j/handler/QuestionHandler.java
> +    private QuestionService questionService;
```suggestion
    private final QuestionService questionService;
```

2021-08-10 03:15 UTC, rsh-12 commented on backend/interview4j/src/main/java/ru/interview4j/service/QuestionService.java
> +    public Mono<Void> update(Question q){
Этот метод находит объект по айди и его же сохраняет в базу данных, при этом никак не изменяя его. Вопрос: для чего этот метод?

2021-08-10 03:15 UTC, rsh-12 commented on backend/interview4j/src/test/java/ru/interview4j/service/QuestionServiceTest.java
> +    @MockBean
```suggestion
    @Autowired
```

2021-08-10 03:15 UTC, rsh-12 commented on backend/interview4j/src/test/java/ru/interview4j/service/QuestionServiceTest.java
> +    @Autowired
```suggestion
    @MockBean
```

2021-08-11 10:03 UTC, Ivanshelemeh commented on backend/interview4j/src/main/java/ru/interview4j/service/QuestionService.java
> +    public Mono<Void> update(Question q){
испарвим

2021-10-11 13:02 UTC, closed without merging